### PR TITLE
Replace screen timeout setting by keep screen on setting

### PR DESCRIPTION
**Pull request by tuomas2**

### CODE REVIEW

**Comment by mjdenham** [comment]
We don't want the screen to stay on indefinitely.  we want it to go off after a certain time.  Originally it defaulted to the default screen timeout and I used to find that 10 mins worked well, but people complained a lot and said they wanted their AB screen timeout to be longer.  But I feel that keeping it on indefinitely would be a backward step.

But reading the wakelock article you linked to does seem to suggest this approach, and it does simplify permissions so I am inclined toward accepting the pull request. What do you think about raising this on the discussion group?

**Comment by tuomas2** [comment]
allright then we need to consider other options.

**Comment by tuomas2** [comment]
In my implementation this option is turned off by default, i.e. screen turns off with default timeout. If setting is turned on, screen stays on.

**Comment by tuomas2** [comment]
Myself I have long system screen off timeout and I have not been using this setting at all.

**Comment by ildar** [comment]
One option book readers use is to keep screen on for a long time until the
device is at least 25% of power. Ref: FBReader

**Comment by mjdenham** [comment]
I am coming round to this option.  Users don't have to turn it on and they still have the option of using the system timeout.

**Comment by tuomas2** [comment]
PR is somehow broken and does not update correctly. Closing this and creating new.

**Comment by tuomas2** [comment]
See https://github.com/tuomas2/and-bible/pull/14

**Pull request closed without merging**
